---
- name: Patch Ubuntu Servers
  hosts: localhost
  gather_facts: false
  vars:
    ansible_connection: community.aws.aws_ssm
    ansible_aws_ssm_instance_id: "{{ lookup('env','SSM_INSTANCE_ID') }}"
    ansible_aws_ssm_bucket_name: "{{ lookup('env','SSM_BUCKET_NAME') }}"
    ansible_become: yes
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes

    - name: Check if a reboot is needed on all servers
      register: reboot_required_file
      stat: path=/var/run/reboot-required

    - name: Output reboot requirement if needed
      debug:
        msg: "Reboot is required on this server."
      when: reboot_required_file.stat.exists
...

